### ISSUE TITLE
Using netCDF mesh files in dynamics 

### ISSUE THREAD

**Issue by pminak** [nextsimhub/nextsimdg#162] opened 2022-09-21 12:57 UTC
Writing a python script that converts and exemplary netCDF files to be handled by dynamics. 
Later we will decide if we directly handle netCDF in c++ or always run conversion in python before starting computations.

**Comment by einola** [comment] 2022-09-23 08:50
In the future, we plan to have that python script as part of the script that builds an init/restart file. The mesh information is then stored in the init file and passed to the dynamics at run time.

**Comment by einola** [comment] 2023-07-31 11:02
Currently, we have a script creating a smesh file from the information in the restart file. The model then reads the restart file _and_ the smesh file.

In the future, we'll skip creating the smesh file and read everything from the restart file. We'll leave this until the dynamics are merged and we've confirmed everything is working.

**Comment by timspainNERSC** [comment] 2023-08-16 16:16
> We'll leave this until the dynamics are merged and we've confirmed everything is working.

Since we have a working thermo & dynamics model without this feature, I am moving it from 1 Dynamics Merge to 2 Stand-alone model.

**Comment by timspainNERSC** [comment] 2023-12-13 14:15
A description of the `.smesh` files, taken from the file `run/25km_NH.smesh`.

1. `ParametricMesh 2.0`
2. nx ny
3. Array of coordinates, either as x y pairs in metres for a flat grid or longitude latitude pairs in radians for a spherical grid. nx * ny lines.
4. `landmask `npoints
   * npoints = nx * ny
6. Array of landmask values. 0 is land, 1 is ocean. nx * ny lines.
7. `dirichlet `nbdy
    * nbdy = the number of edges which have a zero velocity constraint
8. The `dirichlet` section details which boundaries have a zero velocity condition. Each line consists of an element index and the edge label of the edge of that element which has a zero velocity constraint. The labels are:
   * 0 bottom, -y
   * 1 right, +x
   * 2 top, +y
   * 3 left, -x

**Closed** 2024-04-04 11:41 UTC
Labels: enhancement
